language: python
dist: xenial

python:
 - 3.6
 - 3.7
 - 3.8
 - 3.9

env:
 - DJANGO=2.2
 - DJANGO=3.0
 - DJANGO=3.1
 - DJANGO=master

matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8

  allow_failures:
    - env: DJANGO=master

install: pip install tox-travis codecov
script: tox
after_success: codecov
